import type { Metadata } from 'next'
import './globals.css'
import Providers from './providers'

export const metadata: Metadata = {
  title: 'Hono | nextjs',
  description: 'Generated by hono'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="zh-CN" className="dark">
      <head>
        {/* 引入LXGW WenKai Screen字体 */}
        <link 
          rel="stylesheet" 
          href="https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.7.0/style.css" 
        />
      </head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
